"""Initial schema

Revision ID: 1216b262dbfb
Revises: 
Create Date: 2026-03-12 18:40:31.120490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1216b262dbfb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eval_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('eval_run_id', sa.String(length=255), nullable=False),
    sa.Column('query', sa.String(), nullable=False),
    sa.Column('expected_chunk_ids', sa.JSON(), nullable=False),
    sa.Column('retrieved_chunk_ids', sa.JSON(), nullable=False),
    sa.Column('hit_rate', sa.Float(), nullable=False),
    sa.Column('mrr', sa.Float(), nullable=False),
    sa.Column('faithfulness_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eval_results_eval_run_id'), 'eval_results', ['eval_run_id'], unique=False)
    op.create_table('filing_metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('filing_type', sa.String(length=50), nullable=False),
    sa.Column('period', sa.String(length=50), nullable=False),
    sa.Column('s3_raw_key', sa.String(length=1024), nullable=False),
    sa.Column('s3_processed_key', sa.String(length=1024), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('chunk_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETE', 'FAILED', name='ingestionstatus'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_filing_metadata_ticker'), 'filing_metadata', ['ticker'], unique=False)
    op.create_table('query_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('query_text', sa.String(), nullable=False),
    sa.Column('retrieved_chunk_ids', sa.JSON(), nullable=False),
    sa.Column('llm_response', sa.String(), nullable=False),
    sa.Column('citations', sa.JSON(), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('feedback_score', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_query_logs_session_id'), 'query_logs', ['session_id'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_query_logs_session_id'), table_name='query_logs')
    op.drop_table('query_logs')
    op.drop_index(op.f('ix_filing_metadata_ticker'), table_name='filing_metadata')
    op.drop_table('filing_metadata')
    op.drop_index(op.f('ix_eval_results_eval_run_id'), table_name='eval_results')
    op.drop_table('eval_results')
    # ### end Alembic commands ###
